#! /bin/sh

# Kill all of the old process
killall sxhkd
killall picom
killall fcitx
killall nm-applet
killall udiskie
killall syncthing-gtk
killall polkitd
killall birdtray

# Respawn all of the daemons, applets, other misc processes
sxhkd &
~/.config/polybar/launch.sh &
picom -b --respect-prop-shadow -i 0.8 --vsync -D 5 &
fcitx &
nm-applet &
udiskie --tray &
syncthing-gtk --minimized &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
~/.fehbg &
birdtray &

xsetroot -cursor_name left_ptr
xset r rate 200 35
xdo lower -N Polybar

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config automatic_scheme longest_side

# BSPWM rules
bspc rule -a Spotify desktop='^10'
bspc rule -a Thunderbird desktop='^9'
bspc rule -a feh state=floating
bspc rule -a System-config-printer.py state=floating
bspc rule -a Zathura state=tiled

# dropdownname="dropdown"
# bspc query -N -n .hidden >/dev/null || setsid $TERMINAL -n "$dropdownname" -e dropdown >/dev/null 2>&1 &
# bspc rule -a St:$dropdownname hidden=on
# bspc rule -a St:$dropdownname sticky=on
# bspc rule -a St:$dropdownname state=floating
