#! /bin/sh

# Autostart programs
bspstart

xsetroot -cursor_name left_ptr
xset r rate 200 35
xdo lower -N Polybar

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config automatic_scheme     alternate

# BSPWM application rules
bspc rule -a Spotify desktop='^10'
bspc rule -a Thunderbird desktop='^9'
bspc rule -a feh state=floating
bspc rule -a System-config-printer.py state=floating
bspc rule -a Zathura state=tiled
bspc rule -a KeePassXC state=floating
