#!/bin/sh
# Simple script to autostart programs upon boot

# For some reason, some application (ie., Firefox) does not play well with
# pgrep. Funnily enough, same can be said for pidof as well for some
# application... So here we are..
run()
{
	pgrep $1 || pidof $1 || setsid $@ &
}

# Run Gnome keyring
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
run fcitx
run dunst
run udiskie --tray
run syncthing-gtk --minimized
run redshift-gtk
run polkitd
run picom -b -D 5 -f --experimental-backends
run thunderbird
