#!/bin/bash

ICON=$HOME/.scripts/lock.png
TMPBG=/tmp/screen.jpg
maim /tmp/screen.jpg
convert $TMPBG -blur 0x4 $ICON -gravity center -composite -matte $TMPBG
convert $TMPBG RGB:- | i3lock -u --raw $(xrandr | grep \* | awk {'print $1'}):rgb --image /dev/stdin
