#!/bin/bash

dir="/home/kyokeun/Pictures/ss"

fullpath="$dir/$(date +%s)_$(date +%m)_$(date +%d).png"
prog="maim -u"

if pidof -o %PPID -x "$0"; then
	exit 0
fi

# screenshot="$(mktemp --suffix screenshot.png)"
# maim "${screenshot}"
# feh "${screenshot}" &
# feh_pid=$!

case "$(printf "a selected area\\ncurrent window\\nfull screen\\na selected area (copy)\\ncurrent window (copy)\\nfull screen (copy)" | rofi -dmenu -i -p "Screenshot prompt")" in
	"a selected area") $prog -s "$fullpath" ;;
	"current window") $prog -i "$(xdotool getactivewindow)" "$fullpath" ;;
	"full screen") sleep 0.2 && $prog "$fullpath" ;;
	"a selected area (copy)") $prog -s | xclip -selection clipboard -t image/png ;;
	"current window (copy)") $prog -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png ;;
	"full screen (copy)") sleep 0.2 && $prog | xclip -selection clipboard -t image/png ;;
esac

# kill -SIGKILL ${feh_pid}
# rm "${screenshot}"
