#!/bin/bash

dir="/home/kyokeun/Pictures/ss"

fullpath="$dir/$(date +%m)_$(date +%d)_$(date +%s).png"

if pidof -o %PPID -x "$0"; then
	exit 0
fi

screenshot="$(mktemp --suffix screenshot.png)"
maim "${screenshot}"
feh "${screenshot}" &
feh_pid=$!

case "$(printf "a selected area\\ncurrent window\\nfull screen\\na selected area (copy)\\ncurrent window (copy)\\nfull screen (copy)" | rofi -dmenu -i -p "Screenshot prompt")" in
	"a selected area") maim -s "$fullpath" ;;
	"current window") maim -i "$(xdotool getactivewindow)" "$fullpath" ;;
	"full screen") sleep 0.2 && maim "$fullpath" ;;
	"a selected area (copy)") maim -s | xclip -selection clipboard -t image/png ;;
	"current window (copy)") maim -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png ;;
	"full screen (copy)") sleep 0.2 && maim | xclip -selection clipboard -t image/png ;;
esac

kill -SIGKILL ${feh_pid}
rm "${screenshot}"
