#!/bin/sh

OVPN="$(ls ~/*.ovpn)"
OVPN="$(basename ${OVPN%.*})"

SERVICE="openvpn-client@$OVPN.service"

if (systemctl -q is-active $SERVICE); then
	echo "Turning off OpenVPN..."
	sudo systemctl stop $SERVICE
else
	echo "Turning on OpenVPN..."
	sudo systemctl start $SERVICE
fi
