#!/bin/sh

FILE="$(basename $(ls ~/*.ovpn))"
OVPN="${FILE%.*}"

SERVICE="openvpn-client@$OVPN.service"

if (systemctl -q is-active $SERVICE); then
	echo "Turning off OpenVPN..."
	sudo systemctl stop $SERVICE
else
	echo "Turning on OpenVPN..."
	sudo systemctl start $SERVICE
fi

kill -45 $(pidof dwmblocks)
