#!/bin/bash

CMD=$TERMINAL
CWD=''

# Get window ID
ID=$(xdpyinfo | grep focus | cut -f4 -d " ")

# Get PID of process whose window this is
PID=$(xprop -id $ID | grep -m 1 PID | cut -d " " -f 3)
echo "$PID"

# Get last child process (shell, vim, etc)
if [ -n "$PID" ]; then
	CWD="$(readlink -e /proc/"$(pgrep -P "$(xdo pid)" | tail -n 1)"/cwd)"
fi

if [ -n "$CWD" ]; then
	cd $CWD && $CMD
else
	$CMD
fi
