#!/bin/sh

errorout() {
	echo "Usage: vpnctl [ mullvad | wg | status ]"
	exit 1
}

# TODO: Make it compatible with Mullvad

# Interace which all my clients use to access wireguard instance
WGIF="wg0"
WGUP="$(ip link | grep "$WGIF")"
# Check status of mullvad
MULLVADUP="$(mullvad status | awk '{print $3}' 2>/dev/null)"

case $1 in
	mullvad)
		[ "$WGUP" ] \
			&& notify-send "Wireguard is connected. Disconnecting..." \
			&& wg-quick down wg0

		! command -v mullvad > /dev/null && echo "Mullvad not found! Is it installed?" && exit 1

		if [ "$MULLVADUP" = "Disconnected" ]; then
			notify-send "Connecting to mullvad..."
			mullvad connect
		else
			notify-send "Disconnecting to mullvad..."
			mullvad disconnect
		fi

		kill -45 $(pidof dwmblocks)
		;;
	wg)
		! command -v wg-quick > /dev/null \
			&& echo "wg-quick command is not found. On arch, install wireguard-tools" \
			&& exit 1

		[ ! "$MULLVADUP" = "Disconnected" ] \
			&& notify-send "Mullvad is connected. Disconnecting..." \
			&& mullvad disconnect

		if [ "$WGUP" ]; then
			notify-send "Disconnecting to wireguard..."
			wg-quick down wg0
		else
			notify-send "Connecting to wireguard..."
			wg-quick up wg0
		fi

		kill -45 $(pidof dwmblocks)
		;;
	status)
		command -v mullvad > /dev/null \
			&& [ "$MULLVADUP" = "Connected" ] \
			&& echo "MULLVAD" && exit 0
		command -v mullvad > /dev/null \
			&& [ "$MULLVADUP" = "Connecting" ] \
			&& echo "MV (connecting)" && exit 0

		[ "$WGUP" ] && echo "WG" && exit 0
		echo "Disconnected"
		;;
	*)
		errorout
		;;
esac
