#!/bin/sh

unread="$(find "$HOME"/Mail/*/INBOX/new/* -type f 2>/dev/null | wc -l 2>/dev/null)"

pidof mbsync >/dev/null 2>&1 && icon=""

[ "$unread" = "0" ] && [ "$icon" = "" ] && echo "0" || echo "$unread $icon"
