#!/bin/bash
# Purpose of this script is to sync all the dotfiles/rice with my gitlab repository

REPO=~/Documents/i3_arch_rice/
FILE=~/.scripts/dotlist
LIST=`tr '\n' ' ' < $FILE | sed "s@~@$HOME@g"`

# Checking the arguments 
case "$1" in
	push)
		for ITEM in $LIST
		do
			DIR=`dirname "${ITEM}" | sed "s@$HOME@@g"`
			cp -r $ITEM $REPO$DIR
		done
		;;
	pull)
		for ITEM in $LIST
		do
			DIR=`dirname "${ITEM}" | sed "s@$HOME@@g"`
			cp -r $REPO$DIR
		done
		;;
	*)
		echo "Invalid argument. Exiting..."
		exit 1
		;;
esac

