#!/bin/bash
# Purpose of this script is to sync all the dotfiles/rice with my gitlab repository

REPO=~/Documents/i3_arch_rice/
FILE=~/.scripts/dotlist
LIST=`tr '\n' ' ' < $FILE | sed "s@~@$HOME@g"`

for ITEM in $LIST
do
	DIR=`dirname "${ITEM}" | sed "s@$HOME@@g"`
	cp -r $ITEM $REPO$DIR
done
