#!/bin/bash

rm -f /tmp/locked.png

#  If `imagemagick` is not installed, use a blank screen
[[ -f /usr/bin/convert ]] &&
	scrot -m -z /tmp/base.png &&
	# pgrep -x dunst && notify-send -i ~/.scripts/lock.png "Locking computer..." &&
	convert /tmp/base.png -blur 0x8 /tmp/locked.png

# Pause music (mocp, mpd and send the pause key to all mpv videos):
# mocp -P &>/dev/null
# mpc pause &> /dev/null
# pauseallmpv &> /dev/null

i3lock -e -f -c 000000 -i /tmp/locked.png
