#!/bin/bash
# main wrapper to be used with i3 config
# -s is used to select certain section. -e is used to select entire screen

ERRORMSG='Usage:\n\tprintscreen [ -s | -e ] [ path to store picture ]'

# Check for parameters
[ -z $1 ] || [ -z $2 ] || [ ! -d "$2" ] && echo -e $ERRORMSG && exit 1

FULLPATH=$2/$(date +%m)_$(date +%d)_$(date +%s).png

opt=$(getopt -o se -- "$1")
echo $?
[ $? -ne 0 ] && echo -e $ERRORMSG && exit 1
eval set -- "$opt"
while true; do
	case "$1" in
		-s)
			maim -s $FULLPATH
			;;
		-e)
			maim $FULLPATH
			;;
		--)
			shift
			break
			;;
	esac
	shift
done

cat $FULLPATH | xclip -selection clipboard -t image/png
